---
swagger: '2.0'
info:
  description: >-
    This is a Microservice developed under Python, it uses the PyMS
    Microservice pattern and its main functionality is to support of academia.
  version: 1.0.0
  title: Academic System Microservice
tags:
  - name: Academic System
    description: >-
      This Microservice has functionality to process and configure all the requests
      made to the academic system.
  - name: Manage Student
    description: >-
      The functionality of this endpoint is to manage the students entering or
      leaving the institution.
paths:
  /student/manage_student:
    post:
      tags:
        - Manage Student
      summary: End point for student setup
      description: Endpoint to configure student
      operationId: manage_student
      consumes:
        - application/json
      produces:
        - application/json
      x-swagger-router-controller: project.views.student
      responses:
        '200':
          description: 'OK'
          schema:
            $ref: '#/definitions/responseConfigValidation'
      parameters:
        - in: body
          name: data
          required: true
          schema:
              $ref: '#/definitions/studentRequest'
  /control-action/execute:
    post:
      tags:
        - Control Action
      summary: The requestor asks the receiver to start executing control actions for the devices
      description: >-
        Ajustar
      consumes:
        - application/json
      produces:
        - application/json
      x-swagger-router-controller: project.views.control_action
      operationId: execute
      responses:
        '200':
          description: 'The request has succeeded'
          schema:
            $ref: '#/definitions/responseBody'
        '403':
          description: 'The server understood the request but refuses to
                        authorize it'
          schema:
            $ref: '#/definitions/responseBody'
        '500':
          description: 'Internal server error'
          schema:
            $ref: '#/definitions/responseBody'
  /event/get-on-demand:
    post:
      tags:
        - Event
      summary: The requester asks the receiver to start monitoring the events 
               of a set of meters
      description: >-
         Creates the request to return all end device events of specified end
         device types for meters specified by their meter ID.
      consumes:
        - application/json
      produces:
        - application/json
      x-swagger-router-controller: project.views.event
      operationId: get_on_demand
      responses:
        '200':
          description: 'The request has succeeded'
          schema:
            $ref: '#/definitions/responseBody'
        '403':
          description: 'The server understood the request but refuses to authorize it'
          schema:
            $ref: '#/definitions/responseBody'
        '500':
          description: 'Internal server error'
          schema:
            $ref: '#/definitions/responseBody'
  /event/subscribe:
    post:
      tags:
        - Event
      summary: The requester asks the receiver to start monitoring the events 
               of a set of meters
      description: >-
         Ajustar
      consumes:
        - application/json
      produces:
        - application/json
      x-swagger-router-controller: project.views.event
      operationId: subscribe
      responses:
        '200':
          description: 'The request has succeeded'
          schema:
            $ref: '#/definitions/responseBody'
        '403':
          description: 'The server understood the request but refuses to authorize it'
          schema:
            $ref: '#/definitions/responseBody'
        '500':
          description: 'Internal server error'
          schema:
            $ref: '#/definitions/responseBody'
  /external-system/check-state:
    post:
      tags:
        - External system
      summary: Responds with the current state of a requested system component
      description: >-
        This method aims to verify the status of all or each one of the components that are part
        of the API
      consumes:
        - application/json
      produces:
        - application/json
      x-swagger-router-controller: project.views.external_system
      operationId: check_state
      parameters:
        - name: component
          in: query
          required: false
          type: string
      responses:
        '200':
          description: The request has succeeded
          schema:
            $ref: '#/definitions/responseBody'
        '403':
          description: The server understood the request but refuses to authorize it
          schema:
            $ref: '#/definitions/responseBody'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/responseBody'
  /external-system/get-capabilities:
    post:
      tags:
        - External system
      summary: Generates and send the command to get the methods supported by an external system
      description: >-
        This method sends a command to obtain the capabilities of an external system,
        that is, the requested command must consult the external system for
        the methods supported and configured in this
      consumes:
        - application/json
      produces:
        - application/json
      x-swagger-router-controller: project.views.external_system
      operationId: get_capabilities
      parameters:
        - name: component
          in: query
          required: false
          type: string
      responses:
        '200':
          description: The request has succeeded
          schema:
            $ref: '#/definitions/responseBody'
        '403':
          description: The server understood the request but refuses to authorize it
          schema:
            $ref: '#/definitions/responseBody'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/responseBody'
  /external-system/get-identifier:
    post:
      tags:
        - External system
      summary: Generates and sends the command to query the identifier of an external system
      description: >-
          This method sends a command to query the identifier of an external system
          required to perform various operations
      consumes:
        - application/json
      produces:
        - application/json
      x-swagger-router-controller: project.views.external_system
      operationId: get_identifier
      parameters:
        - name: component
          in: query
          required: false
          type: string
      responses:
        '200':
          description: The request has succeeded
          schema:
            $ref: '#/definitions/responseBody'
        '403':
          description: The server understood the request but refuses to authorize it
          schema:
            $ref: '#/definitions/responseBody'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/responseBody'
  /metering-system/discover:
    post:
      tags:
        - Metering System
      summary: Request the consultation for the configuration of the metering systems
      description: >-
        This method requests the execution of the necessary commands to consult all
        the data necessary to configure the measurement systems
      consumes:
        - application/json
      produces:
        - application/json
      x-swagger-router-controller: project.views.metering_system
      operationId: discover
      responses:
        '200':
          description: 'The request has succeeded'
          schema:
            $ref: '#/definitions/responseBody'
        '403':
          description: 'The server understood the request but refuses to authorize it'
          schema:
            $ref: '#/definitions/responseBody'
        '500':
          description: 'Internal server error'
          schema:
            $ref: '#/definitions/responseBody'
  /reading/get-on-demand:
    post:
      tags:
        - Reading
      summary: The requester asks the receiver for demand readings from
               a group of meters
      description: >-
        Ajustar
      consumes:
        - application/json
      produces:
        - application/json
      x-swagger-router-controller: project.views.reading
      operationId: get_on_demand
      responses:
        '200':
          description: 'The request has succeeded'
          schema:
            $ref: '#/definitions/responseBody'
        '403':
          description: 'The server understood the request but refuses to authorize it'
          schema:
            $ref: '#/definitions/responseBody'
        '500':
          description: 'Internal server error'
          schema:
            $ref: '#/definitions/responseBody'
  /schedule/create-reading-schedule:
    post:
      tags:
        - Schedule
        - Reading
      summary: The requestor asks the receiver to program the reading of
               measurements from a group of meters
      description: >-
        Ajustar
      consumes:
        - application/json
      produces:
        - application/json
      x-swagger-router-controller: project.views.schedule
      operationId: create_reading_schedule
      responses:
        '200':
          description: 'The request has succeeded'
          schema:
            $ref: '#/definitions/responseBody'
        '403':
          description: 'The server understood the request but refuses to authorize it'
          schema:
            $ref: '#/definitions/responseBody'
        '500':
          description: 'Internal server error'
          schema:
            $ref: '#/definitions/responseBody'
  /schedule/enable-reading-schedule:
    post:
      tags:
        - Schedule
      summary: Ajustar
      description: >-
        Ajustar
      consumes:
        - application/json
      produces:
        - application/json
      x-swagger-router-controller: project.views.schedule
      operationId: enable_reading_schedule
      responses:
        '200':
          description: 'The request has succeeded'
          schema:
            $ref: '#/definitions/responseBody'
        '403':
          description: 'The server understood the request but refuses to authorize it'
          schema:
            $ref: '#/definitions/responseBody'
        '500':
          description: 'Internal server error'
          schema:
            $ref: '#/definitions/responseBody'
definitions:
  studentRequest:
    type: object
    properties:
      studentName:
          type: string
      studentLastName:
          type: string
      birthDate:
          type: string
      gender:
          type: string
      action:
          type: string
  courseRequest:
    type: object
    properties:
      name_course:
          type: string
      course_start_date:
          type: string
      course_end_date:
          type: string
  addressRequest:
    type: object
    properties:
      name_course:
          type: string
      course_start_date:
          type: string
      course_end_date:
          type: string
  responseConfigValidation:
    type: object
    properties:
      apiVersion:
        type: string
      data:
        type: array
        items:
          $ref: '#/definitions/logTopology'
      details:
        type: array
        items:
          $ref: '#/definitions/responseDetail'
      statusCode:
        type: integer
      method:
        type: string
  responseDetail:
    type: object
    properties:
      code:
        type: string
      values:
        type: array
        items:
          type: string
      type:
        type: string
  logTopology:
    type: object
    properties:
      guidFile:
        type: string
      process:
        type: string
      action:
        type: boolean
      entityName1:
        type: string
      entityId1:
        type: string
      entityName2:
        type: string
      entityId2:
        type: string
  responseBody:
    type: object
    properties:
      method:
        type: string
      apiVersion:
        type: string
      data:
        type: array
        items:
          type: object
      details:
        type: array
        items:
          $ref: '#/definitions/responseBodyDetail'
      statusCode:
        type: integer
  responseBodyDetail:
    type: object
    properties:
      message:
        type: string
      values:
        type: array
        items:
          type: string
      level:
        type: string
