pyms:
    services:
      swagger:
          path: "swagger"
          file: "swagger.yml"
          url: "/swagger/"
          project_dir: "project"
    config:
      APP_NAME: "Interoperability Microservice"
      APP_VERSION: "1.0.0"
      APPLICATION_ROOT : "/interoperability"
      AWS_SQS_ACCESS_KEY_ID: "AKIAYP2Z4Y6TMNKJXVFN"
      AWS_SQS_REGION_NAME: "us-east-1"
      AWS_SQS_SECRET_ACCESS_KEY: "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"
      CONNECTION_STRINGS:
        # REDIS_EC_CROSS: "host=ec-storage-cache.zfybl7.ng.0001.use1.cache.amazonaws.com,port=6379"
        # REDIS_EC_CROSS: "host=ec-storage-cache.zfybl7.ng.0001.use1.cache.amazonaws.com,port=16379"
        REDIS_EC_CROSS: "host=localhost,port=16379"
      DATABASE_CACHE_KEYS:
        EVENT_TYPE_CODE: "eventTypeCodes"
        EXTERNAL_SYSTEMS: "externalSystems-configurations"
        EXTERNAL_SYSTEM_CAPABILITIES: "externalSystemCapabilities-{}-{}"
        TRANSACTIONS: "transactions-{}"
        READING_TYPE_CODE: "readingTypeCodes-{}"
        VARIABLE: "variables-{}"
      DEBUG: true
      LANGUAGE_MULTI_SPEAK_DEFAULT_VERSION: "5.0.0"
      QUEUE_COMMAND_NAME: "sqs-command"
      QUEUE_INTEROPERABILITY_NAME: "sqs-interoperability"
      QUEUE_PARAMETER_NAME: "sqs-parameter"
      QUEUE_LOG_NAME: "sqs-logs"
      TESTING: true